# entorno de ejecución y versión
language: node_js
node_js:
  - latest

# aceleración de los procesos npm por caché
cache:
  directories:
    - "$HOME/.npm"
    - "node_modules"

# No esperar a que todas las ejecuciones terminen
matrix:
  - fast_finish: true

include:
  # Backend setup
  - env: NestJS
    before_script:
      - cd ${TRAVIS_BUILD_DIR}/backend  # Cambia al directorio del backend.
      - npm install -g @nestjs/cli
      - npm install  # Instala las dependencias del backend.
    script:
      - npm run test  # Ejecuta las pruebas del backend.

  # Frontend setup    
  - env: VueJS
    before_script:
      - cd ${TRAVIS_BUILD_DIR}/frontend  # Cambia al directorio del frontend.
      - npm install  # Instala las dependencias del frontend.
    script:
      - npm run test:e2e  # Ejecuta las pruebas del frontend.

on:
  branch: master