version: '3.7'

services:
  nestjs:
    container_name: devon-backend
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: docker/dockerfile
    volumes:
      - ../:/usr/src/app
      - ../node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229 # Para tests
      - 3100:8080

# Container name: backtest
# localhost: 8081
# Container port: 8081
# Volumen:
#   Host path: (pwd)
#   Container path: /usr/src/app