version: '3.8'

networks:
  backfront-net:

services:
  backend-nestjs:
    restart: always
    image: "node:20.9-bookworm-slim"
    env_file:
      - ./backend/.env
    working_dir: /srv/backend
    volumes:
      - ./backend/:/srv/backend
    ports:
      - 3000:3000
      - 9229:9229 # Para tests
    command: "npm run start:dev"
    networks:
      - backfront-net

  frontend-vuejs:
    image: "node:20.9-bookworm-slim"
    working_dir: /srv/frontend
    volumes:
      - ./frontend/public:/srv/frontend/public
      - ./frontend/src:/srv/frontend/src
      - ./frontend/index.html:/srv/frontend/index.html
      - ./frontend/package.json:/srv/frontend/package.json
      - ./frontend/tsconfig.json:/srv/frontend/tsconfig.json
      - ./frontend/tsconfig.node.json:/srv/frontend/tsconfig.node.json
      - ./frontend/vite.config.ts:/srv/frontend/vite.config.ts
    ports:
      - 8080:8080
      - 8081:8081
      - 4173:4173
      - 4174:4174
    command: bash -c "npm install && npm run dev"
    networks:
      - backfront-net