services:
  - type: web
    name: backend-nestjs
    rootDir: backend
    runtime: node
    buildCommand: npm install
    startCommand: npm run start:dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

  - type: web
    name: frontend-vuejs
    rootDir: frontend
    runtime: node
    buildCommand: npm install
    startCommand: npm run build && npx http-server dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080