name: CI Cypress - Testing e2e

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Clone or Update Backend Repository
        run: git clone https://github.com/dkaerit/nest-api-rest.git

      - name: Install NestJS CLI
        run: npm install -g @nestjs/cli

      - name: Start Backend
        working-directory: nest-api-rest
        run: npm run start

      - name: Wait for Backend
        working-directory: frontend
        run: wait-for-it -t 0 localhost:3000

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./frontend
          browser: chrome
          start: npm run start
          wait-on: "http://localhost:8080"

      - name: Run Tests
        working-directory: frontend
        run: npm run test

