name: CI Cypress - Testing e2e

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/Copy Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clone Backend Repository
        run: git clone https://github.com/dkaerit/nest-api-rest.git

      - name: Install NestJS CLI
        run: npm install -g @nestjs/cli

      - name: Install Backend Dependencies
        working-directory: nest-api-rest
        run: npm install
          
      - name: Start Backend Server
        working-directory: nest-api-rest
        run: npm run start &

  frontend:
    needs: backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/Copy Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          working-directory: frontend
          project: ./frontend
          browser: chrome
          start: npm run start
          wait-on: "http://localhost:8080"

      - name: Run Tests
        working-directory: frontend
        run: npm run test
